/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageScale */

#ifndef _Included_ImageScale
#define _Included_ImageScale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImageScale
 * Method:    imageScale
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ImageScale_imageScale
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
